import { auth } from "@/auth";
import { Geist, Geist_Mono } from "next/font/google";
import { FriendProvider } from "./context/FriendContext";
import { ScreenProvider } from "./context/ScreenContext";
import { SocketProvider } from "./context/SocketContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider session={session}>
          <ScreenProvider>
            <FriendProvider>{children}</FriendProvider>
          </ScreenProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
